services:
  symfony-dc-php:
    platform: linux/amd64
    image: webdevops/php-nginx:8.3
    container_name: symfony-dc-php
    working_dir: /var/www
    networks:
      - symfony-dc-network
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public

  symfony-dc-mysql:
    container_name: symfony-dc-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - symfony-dc-data:/var/lib/mysql
    networks:
      - symfony-dc-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: symfony_dc
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  symfony-dc-data:

networks:
  symfony-dc-network:
    driver: bridge
